Description: Base Template to create Neptune Stack inside a VPC
Parameters:
  Env:
    Description: Environment tag, e.g. prod, nonprod.
    Default: test
    Type: String
    AllowedPattern: "[a-z0-9]+"
    MaxLength: 15
  DbInstanceType:
    Description: Neptune DB instance type
    Type: String
    Default: db.t3.medium
    AllowedValues:
      - db.t3.medium
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.12xlarge
    ConstraintDescription: Must be a valid Neptune instance type.
  DBReplicaIdentifierSuffix:
    Description: "OPTIONAL: The ID for the Neptune Replica to use. Empty means no read replica."
    Type: String
    Default: ""
  DBClusterPort:
    Type: String
    Default: "8182"
    Description: Enter the port of your Neptune cluster
  NeptuneQueryTimeout:
    Type: Number
    Default: 20000
    Description: Neptune Query Time out (in milliseconds)
  NeptuneEnableAuditLog:
    Type: Number
    Default: 0
    AllowedValues:
      - 0
      - 1
    Description: Enable Audit Log. 0 means disable and 1 means enable.
  IamAuthEnabled:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable IAM Auth for Neptune.
  AttachBulkloadIAMRoleToNeptuneCluster:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Attach Bulkload IAM role to cluster
  StorageEncrypted:
    Description: Enable Encryption for Neptune.
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  KmsKeyId:
    Description: "OPTIONAL: If StorageEncrypted is true, the Amazon KMS key identifier for the encrypted DB cluster."
    Type: String
    Default: ""
Conditions:
  CreateDBReplicaInstance: !Not
    - !Equals
      - !Ref "DBReplicaIdentifierSuffix"
      - ""
  AZ3NotPresent: !Or
    - !Equals
      - !Ref "AWS::Region"
      - ca-central-1
    - !Equals
      - !Ref "AWS::Region"
      - us-west-1
  AZ3Present: !Not
    - !Condition "AZ3NotPresent"
  AttachBulkloadIAMRoleToNeptuneClusterCondition: !Equals
    - !Ref "AttachBulkloadIAMRoleToNeptuneCluster"
    - "true"
Mappings:
  ServicePrincipalMap:
    aws:
      EC2ServicePrincipal: ec2.amazonaws.com
    aws-cn:
      EC2ServicePrincipal: ec2.amazonaws.com.cn
    aws-us-gov:
      EC2ServicePrincipal: ec2.amazonaws.com
Resources:
  NeptuneDBSubnetGroup:
    Type: AWS::Neptune::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Neptune DB subnet group
      SubnetIds: !If
        - AZ3NotPresent
        - - !Ref "Subnet1"
          - !Ref "Subnet2"
        - - !Ref "Subnet1"
          - !Ref "Subnet2"
          - !Ref "Subnet3"
      Tags:
        - Key: Name
          Value: !Sub "Neptune-${Env}"
        - Key: StackId
          Value: !Sub "${AWS::StackId}"
        - Key: Stack
          Value: !Sub "${AWS::Region}-${AWS::StackName}"
        - Key: Application
          Value: NeptuneCloudformation
  NeptuneSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref "VPC"
      GroupDescription: Allow Access
      SecurityGroupIngress:
        - FromPort: !Ref "DBClusterPort"
          ToPort: !Ref "DBClusterPort"
          IpProtocol: tcp
          CidrIp: "0.0.0.0/0"
          Description: http access
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"
          Description: outbound anywhere
      Tags:
        - Key: Name
          Value: !Sub "Neptune-${Env}"
        - Key: StackId
          Value: !Sub "${AWS::StackId}"
        - Key: Stack
          Value: !Sub "${AWS::Region}-${AWS::StackName}"
        - Key: Application
          Value: NeptuneCloudformation
  NeptuneDBClusterParameterGroup:
    Type: AWS::Neptune::DBClusterParameterGroup
    Properties:
      Family: neptune1
      Description: test-cfn-neptune-db-cluster-parameter-group-description
      Parameters:
        neptune_enable_audit_log: !Ref "NeptuneEnableAuditLog"
      Tags:
        - Key: Name
          Value: !Sub "Neptune-${Env}"
        - Key: StackId
          Value: !Sub "${AWS::StackName}"
        - Key: Stack
          Value: !Sub "${AWS::Region}-${AWS::StackId}"
        - Key: Application
          Value: NeptuneCloudformation
  NeptuneDBParameterGroup:
    Type: AWS::Neptune::DBParameterGroup
    Properties:
      Family: neptune1
      Description: test-cfn-neptune-db-parameter-group-description
      Parameters:
        neptune_query_timeout: !Ref "NeptuneQueryTimeout"
      Tags:
        - Key: Name
          Value: !Sub "Neptune-${Env}"
        - Key: StackId
          Value: !Sub "${AWS::StackId}"
        - Key: Stack
          Value: !Sub "${AWS::Region}-${AWS::StackName}"
        - Key: Application
          Value: NeptuneCloudformation
  NeptuneDBCluster:
    Type: AWS::Neptune::DBCluster
    Properties:
      DBSubnetGroupName: !Ref "NeptuneDBSubnetGroup"
      VpcSecurityGroupIds:
        - !GetAtt "VPC.DefaultSecurityGroup"
        - !Ref "NeptuneSG"
      DBClusterParameterGroupName: !Ref "NeptuneDBClusterParameterGroup"
      Port: !Ref "DBClusterPort"
      IamAuthEnabled: !Ref "IamAuthEnabled"
      StorageEncrypted: !Ref "StorageEncrypted"
      KmsKeyId: !Ref "KmsKeyId"
      Tags:
        - Key: Name
          Value: !Sub "Neptune-${Env}"
        - Key: StackId
          Value: !Sub "${AWS::StackId}"
        - Key: Stack
          Value: !Sub "${AWS::Region}-${AWS::StackName}"
        - Key: Application
          Value: NeptuneCloudformation
    DependsOn:
      - NeptuneDBSubnetGroup
      - NeptuneDBClusterParameterGroup
  NeptuneDBInstance:
    Type: AWS::Neptune::DBInstance
    Properties:
      DBClusterIdentifier: !Ref "NeptuneDBCluster"
      DBInstanceClass: !Ref "DbInstanceType"
      DBParameterGroupName: !Ref "NeptuneDBParameterGroup"
      Tags:
        - Key: Name
          Value: !Sub "Neptune-${Env}"
        - Key: StackId
          Value: !Sub "${AWS::StackId}"
        - Key: Stack
          Value: !Sub "${AWS::Region}-${AWS::StackName}"
        - Key: Application
          Value: NeptuneCloudformation
    DependsOn:
      - NeptuneDBCluster
      - NeptuneDBParameterGroup
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.30.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: !Sub "Neptune-${Env}"
        - Key: StackId
          Value: !Sub "${AWS::StackId}"
        - Key: Stack
          Value: !Sub "${AWS::Region}-${AWS::StackName}"
        - Key: Application
          Value: NeptuneCloudformation
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref "VPC"
    DependsOn:
      - VPC
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref "VPC"
    DependsOn:
      - VPC
  IGWAtt:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref "IGW"
      VpcId: !Ref "VPC"
    DependsOn:
      - VPC
      - IGW
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "Neptune-${Env}"
        - Key: StackId
          Value: !Sub "${AWS::StackId}"
        - Key: Stack
          Value: !Sub "${AWS::Region}-${AWS::StackName}"
        - Key: Application
          Value: NeptuneCloudformation
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref "IGW"
      RouteTableId: !Ref "PublicRouteTable"
    DependsOn:
      - IGWAtt
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.30.1.0/24
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select
        - 0
        - !GetAZs ""
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.30.2.0/24
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select
        - 1
        - !GetAZs ""
  Subnet3:
    Type: AWS::EC2::Subnet
    Condition: AZ3Present
    Properties:
      CidrBlock: 172.30.3.0/24
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select
        - 2
        - !GetAZs ""
  Subnet4:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.30.4.0/24
      MapPublicIpOnLaunch: "true"
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select
        - 0
        - !GetAZs ""
  Subnet5:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.30.5.0/24
      MapPublicIpOnLaunch: "true"
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select
        - 1
        - !GetAZs ""
  Subnet6:
    Type: AWS::EC2::Subnet
    Condition: AZ3Present
    Properties:
      CidrBlock: 172.30.6.0/24
      MapPublicIpOnLaunch: "true"
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select
        - 2
        - !GetAZs ""
  SubnetRTAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn:
      - Subnet1
      - PrivateRouteTable
    Properties:
      RouteTableId: !Ref "PrivateRouteTable"
      SubnetId: !Ref "Subnet1"
  SubnetRTAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn:
      - Subnet2
      - PrivateRouteTable
    Properties:
      RouteTableId: !Ref "PrivateRouteTable"
      SubnetId: !Ref "Subnet2"
  SubnetRTAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: AZ3Present
    DependsOn:
      - Subnet3
      - PrivateRouteTable
    Properties:
      RouteTableId: !Ref "PrivateRouteTable"
      SubnetId: !Ref "Subnet3"
  SubnetRTAssociation4:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn:
      - Subnet4
      - PublicRouteTable
    Properties:
      RouteTableId: !Ref "PublicRouteTable"
      SubnetId: !Ref "Subnet4"
  SubnetRTAssociation5:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn:
      - Subnet5
      - PublicRouteTable
    Properties:
      RouteTableId: !Ref "PublicRouteTable"
      SubnetId: !Ref "Subnet5"
  SubnetRTAssociation6:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: AZ3Present
    DependsOn:
      - Subnet6
      - PublicRouteTable
    Properties:
      RouteTableId: !Ref "PublicRouteTable"
      SubnetId: !Ref "Subnet6"
Outputs:
  DBClusterId:
    Description: Neptune Cluster Identifier
    Value: !Ref "NeptuneDBCluster"
  DBSubnetGroupId:
    Description: Neptune DBSubnetGroup Identifier
    Value: !Ref "NeptuneDBSubnetGroup"
  DBClusterResourceId:
    Description: Neptune Cluster Resource Identifier
    Value: !GetAtt "NeptuneDBCluster.ClusterResourceId"
  DBClusterEndpoint:
    Description: Master Endpoint for Neptune Cluster
    Value: !GetAtt "NeptuneDBCluster.Endpoint"
  DBInstanceEndpoint:
    Description: Master Instance Endpoint
    Value: !GetAtt "NeptuneDBInstance.Endpoint"
  SparqlEndpoint:
    Description: Sparql Endpoint for Neptune
    Value: !Join
      - ""
      - - https://
        - !GetAtt "NeptuneDBCluster.Endpoint"
        - ":"
        - !GetAtt "NeptuneDBCluster.Port"
        - /sparql
  GremlinEndpoint:
    Description: Gremlin Endpoint for Neptune
    Value: !Join
      - ""
      - - https://
        - !GetAtt "NeptuneDBCluster.Endpoint"
        - ":"
        - !GetAtt "NeptuneDBCluster.Port"
        - /gremlin
  LoaderEndpoint:
    Description: Loader Endpoint for Neptune
    Value: !Join
      - ""
      - - https://
        - !GetAtt "NeptuneDBCluster.Endpoint"
        - ":"
        - !GetAtt "NeptuneDBCluster.Port"
        - /loader
  DBClusterReadEndpoint:
    Description: DB cluster Read Endpoint
    Value: !GetAtt "NeptuneDBCluster.ReadEndpoint"
  DBClusterPort:
    Description: Port for the Neptune Cluster
    Value: !GetAtt "NeptuneDBCluster.Port"
  PrivateSubnet1:
    Description: Subnet Id
    Value: !Ref "Subnet1"
  PrivateSubnet2:
    Description: Subnet Id
    Value: !Ref "Subnet2"
  PrivateSubnet3:
    Condition: AZ3Present
    Description: Subnet Id
    Value: !Ref "Subnet3"
  PublicSubnet1:
    Description: Subnet Id
    Value: !Ref "Subnet4"
  PublicSubnet2:
    Description: Subnet Id
    Value: !Ref "Subnet5"
  PublicSubnet3:
    Condition: AZ3Present
    Description: Subnet Id
    Value: !Ref "Subnet6"
  VPC:
    Description: VPC
    Value: !Ref "VPC"
  NeptuneSG:
    Description: Neptune Security Group
    Value: !Ref "NeptuneSG"
  InternetGateway:
    Description: "Neptune InternetGateway "
    Value: !Ref "IGW"
