name: Cloudwatch Syntax check

on: [push, pull-request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::080863329876:role/GithubActions
          aws-region: eu-west-1
      - name: Test Cloudwatch Syntax
        run: |
          aws cloudformation validate-template --template-body file://cheap-aws-neptune-stack.yaml
          aws cloudformation validate-template --template-body file://neptune-base-stack.yaml
          aws cloudformation validate-template --template-body file://neptune-workbench-stack.yaml
